

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

exec-once = dunst daemon
exec-once = waybar
exec-once = hypridle

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, P, exec, hyprshot -zm region --clipboard-only



# Cambiar entre workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4

# Mover ventana al workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

windowrule2 = opaity 0.8 0.8,class:^(kitty)$

input {
    kb_layout = es
}

misc {
    mouse_move_enables_dpms = true
}

decoration {
	rounding = 12

	shadow {
		enabled = true
		range = 8
		render_power = 3
		color = rgba(000000aa)
	}
	blur {
		enabled = true
		size = 8
		passes = 2
	}
}


