general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    size = 200, 50
    position = 0, -80
    font_color = rgb(255, 255, 255)
}
